services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Docker/DockerfileBackend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Docker/DockerfileFrontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped